# Now install Dokploy
- name: Install Dokploy
  ansible.builtin.shell:
    cmd: curl -sSL https://dokploy.com/install.sh | sh
  register: dokploy_install
  failed_when: false  # We'll handle the error in the next task